kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: iscsi
provisioner: iscsi
parameters:
  targetPortal: 192.168.99.100:3260
  iqn: iqn.2003-01.org.linux-iscsi.minishift:targetd061409
  iscsiInterface: tcp
  pool: pool0
  