kind: DeploymentConfig
apiVersion: v1
metadata:
  name: iscsi-provisioner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iscsi-provisioner
    spec:
      containers:
        - name: iscsi-provisioner
          image: raffaelespazzoli/iscsi-controller
          args:
            - "start"
          env:
            - name: PROVISIONER_NAME
              value: iscsi
            - name: INITIATOR_WWN
              value: iscsi
            - name: TARGETD_URL
              value: iscsi    
